#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_audio": "00_core.ipynb",
         "ResampleSignal": "00_core.ipynb",
         "AudioBase": "00_core.ipynb",
         "AudioMono": "00_core.ipynb",
         "duration": "00_core.ipynb",
         "SpecImage": "00_core.ipynb",
         "Spectify": "00_core.ipynb",
         "create": "00_core.ipynb",
         "MaskBase": "00_core.ipynb",
         "MaskBinary": "00_core.ipynb",
         "show_batch": "00_core.ipynb",
         "pre_plot": "00_core.ipynb",
         "post_plot": "00_core.ipynb",
         "show": "00_core.ipynb",
         "show_audio": "00_core.ipynb",
         "show_spec": "00_core.ipynb",
         "show_mask": "00_core.ipynb",
         "hear_audio": "00_core.ipynb",
         "Resample": "00_core.ipynb",
         "Clip": "00_core.ipynb",
         "ArrayAudioBase": "00_core.ipynb",
         "ArraySpecBase": "00_core.ipynb",
         "ArrayMaskBase": "00_core.ipynb",
         "TensorAudio": "00_core.ipynb",
         "TensorSpec": "00_core.ipynb",
         "TensorMask": "00_core.ipynb",
         "encodes": "00_core.ipynb",
         "audio2tensor": "00_core.ipynb",
         "spec2tensor": "00_core.ipynb",
         "mask2tensor": "00_core.ipynb",
         "time_bins": "01_utils.ipynb",
         "stft": "01_utils.ipynb",
         "istft": "01_utils.ipynb",
         "setup_graph": "02_plot.ipynb",
         "ColorMeshPlotter": "02_plot.ipynb",
         "cmap_dict": "02_plot.ipynb",
         "cmap": "02_plot.ipynb",
         "get_audio_files": "03_data.ipynb",
         "AudioBlock": "03_data.ipynb",
         "audio_extensions": "03_data.ipynb"}

modules = ["core.py",
           "utils.py",
           "plot.py",
           "data.py"]

git_url = "https://github.com/holyfiddlex/speechsep/tree/master/"

def custom_doc_links(name): return None