#AUTOGENERATED! DO NOT EDIT! File to edit: dev/00_core.ipynb (unless otherwise specified).

__all__ = ['load_audio', 'AudioItem']

#Cell
import fastai2.vision.core as core
import fastai2.vision.data as data
import fastai2.torch_basics as basics

import matplotlib.pyplot as plt
import numpy as np
import scipy
import scipy.io.wavfile
import IPython

from librosa import load
from IPython.display import Audio, display

import speechsep.utils as utils
import speechsep.plot as plot

#Cell
def load_audio(fn, **kwargs):
    return load(fn)

#Cell
class AudioItem():
    def __init__(self, filename):
        self.fn = filename
        self.audio, self.sr = load_audio(self.fn)
    def __repr__(self):
        display(Audio(self.audio, rate=self.sr))
        return f'{self.__str__()}'
    def __str__(self):
        return f'{self.fn}'