#AUTOGENERATED! DO NOT EDIT! File to edit: dev/02_plot.ipynb (unless otherwise specified).

__all__ = ['setup_graph', 'ColorMeshPlotter', 'cmap_dict', 'cmap']

#Cell
from .imports import *

#Cell
def setup_graph(title='', x_label='', y_label='', fig_size=None):
    fig = plt.figure()
    if fig_size != None:
        fig.set_size_inches(fig_size[0], fig_size[1])
    ax = fig.add_subplot(111)
    ax.set_title(title)
    ax.set_xlabel(x_label)
    ax.set_ylabel(y_label)

#Cell
class ColorMeshPlotter():
    def __init__(self, **kwargs):
        self._plot = partial(plt.pcolormesh, **kwargs)
    def __call__(self, spec, title='', x_label='', y_label='', fig_size=None):
        setup_graph(title=title, x_label=x_label, y_label=y_label, fig_size=fig_size)
        self._plot(abs(spec[:spec.shape[0]//2]))

#Cell
cmap_dict = {'red':  ((0.0, 0.0156, 0.0156),
                      (0.3, 1.0, 1.0),
                      (0.6, 1.0, 1.0),
                      (1.0, 1.0, 1.0)),
             'green':((0.0, 0.125, 0.125),
                       (0.3, 1.0, 1.0),
                       (0.6, 1.0, 1.0),
                       (1.0, 1.0, 0.0)),
             'blue': ((0.0, 0.25, 0.25),
                      (0.3, 1.0, 1.0),
                      (0.6, 0.17, 0.17),
                      (1.0, 0.0, 0.0))}
cmap = matplotlib.colors.LinearSegmentedColormap(None,cmap_dict,256)